### ISSUE TITLE
Problem when creating event type with numbers following dots

### ISSUE THREAD

**Issue by rcillo** [zalando/nakadi#307] opened 2016-06-28 15:39 UTC
When creating an event type "event.type.123abc" it fails. It's currently not allowed to have numbers after dots.

```
{
    "status": 422,
    "title": "Unprocessable Entity",
    "detail": "Field \"name\" format not allowed\n",
    "type": "http://httpstatus.es/422"
}
```

**Comment by shuaibiyy** [comment] 2016-11-07 16:21
We just hit into this issue. Please fix 😿

**Comment by valgog** [comment] 2016-12-18 12:33
@zalando/aruha is this fixed?

**Comment by lmontrieux** [comment] 2017-05-29 07:26
@valgog no, it isn't. But now it has a ticket in our Jira: ARUHA-828

**Comment by SergKam** [comment] 2017-05-29 15:36
But this is documented and expected behavior. 
> pattern: '[a-zA-Z][-0-9a-zA-Z_]*(\.[a-zA-Z][-0-9a-zA-Z_]*)*'

Why do we need to fix this? 
https://github.com/zalando/nakadi/blob/master/api/nakadi-event-bus-api.yaml#L2104

**Comment by lmontrieux** [comment] 2017-05-29 16:24
Oh, that's correct. In this case, I will close this issue, since the behaviour is exactly what is expected. Thanks @SergKam .

**Closed by lmontrieux** 2017-05-29 16:24 UTC
Labels: bug, help wanted

**Comment by shuaibiyy** [comment] 2017-05-30 00:01
Hmm.. I think the documentation can be greatly improved :)
